# Generated by Django 5.0.4 on 2024-04-16 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Read Me Date')),
                ('read', models.CharField(choices=[('Small', 'Read a little'), ('Medium', 'Read a bit'), ('Lot', 'Readed A lot')], default='Small', max_length=6)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.manga')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
